### ISSUE TITLE
Prevent private file paths from being exposed to third parties

### ISSUE THREAD

**Issue by ciscorn** [svelte-docgen/svelte-docgen#29]
The current extraction results include private file paths.

In SSR/SSG setups like SvelteKit, the results extracted by the Vite plugin are statically embedded into both the server-side and client-side code, which is efficient. However, this unintentionally exposes private file paths to the client.

Example extraction result:

```js
// ...
        "type": {
          "kind": "union",
          "types": [
            { "kind": "undefined" },
            {
              "kind": "constructible",
              "name": '"/Users/*****/*****/github.com/ciscorn/my-project/node_modules/.pnpm/external-package/node_modules/external-package".LngLat',
              "constructors": [
                [
                  {
                    "name": "lng",
                    "isOptional": false,
                    "type": { "kind": "number" }
                  },
                  {
                    "name": "lat",
                    "isOptional": false,
                    "type": { "kind": "number" }
                  }
                ]
              ],
              "sources": /* @__PURE__ */ new Set([
                "/Users/*****/*****/github.com/ciscorn/my-project/node_modules/.pnpm/external-package/node_modules/external-package/dist/types.d.ts"
              ])
            },
// ...
```

**Comment by xeho91** [comment]
Would trimming left anything prior to the project root directory be sufficient?

Following your example result:

```diff
- /Users/*****/*****/github.com/ciscorn/my-project/node_modules/.pnpm/external-package/node_modules/external-package/dist/types.d.ts
+ /my-project/node_modules/.pnpm/external-package/node_modules/external-package/dist/types.d.ts

**Comment by xeho91** [comment]
Internally, I think it wouldn't affect us.

In the analyser part of this project, for example, checking for `isSnippet` it checks each source entry only the ending of the path. Code example:

https://github.com/svelte-docgen/svelte-docgen/blob/99b4975109c7614fa2649c65027f523691958f9c/packages/svelte-docgen/src/analyzer/prop.js#L63-L73

**Comment by ciscorn** [comment]
Yes, when using docgen through the Vite plugin, I think it would be better if trimming makes Vite’s root the root directory.

```diff
- /Users/*****/*****/github.com/ciscorn/my-project/node_modules/.pnpm/external-package/node_modules/external-package/dist/types.d.ts
+ /node_modules/.pnpm/external-package/node_modules/external-package/dist/types.d.ts
```

**Comment by xeho91** [comment]
Aye, but for the consistency. I think we could just trim to the project root directory. Just exactly like in your example—trim the project directory as well.

Unless there's a reason that it _has_ to be different when using docgen via the Vite plugin that I am not seeing?

**Comment by ciscorn** [comment]
@xeho91 Ah, I think there might be a misunderstanding here. `/Users/*****/*****/github.com/ciscorn/my-project` is the Vite root, so trimming that will result in `/node_modules/.pnpm/external-package/node_modules/external-package/dist/types.d.ts`, just like in my example!
