### ISSUE TITLE
Switch from Biome linter to ESLint

### ISSUE THREAD

**Issue by ciscorn** [svelte-docgen/svelte-docgen#36]
We have already migrated our formatter to Prettier (#24) to align with the setup of the official Svelte repositories. For the same reason, the linter should also be migrated to ESLint.

If Biome adds practical support for Svelte in the future, we may consider switching back.

**Comment by ciscorn** [comment]
https://github.com/sveltejs/eslint-config

**Comment by ciscorn** [comment]
@xeho91 I think the set of script names should also be aligned with the naming conventions in the official Svelte repositories.

just `lint` and `format`.

For reference:
- https://github.com/sveltejs/svelte/blob/main/package.json#L20-L23
- https://github.com/sveltejs/kit/blob/main/package.json#L13-L15

**Comment by xeho91** [comment]
Sure, go ahead. I'm cool with renaming. 👍
