### ISSUE TITLE
Initial setup of the documentation for users

### ISSUE THREAD

**Issue by ciscorn** [svelte-docgen/svelte-docgen#41]
discussion: #33 

- Create the app within this monorepo
- Use [SveltePress](https://sveltepress.site/)
- Deploy on ~~Vercel (for now)~~ 
    - Netlify OSS plan ?
    - Cloudflare OSS plan ?
    - Vercel OSS plan (Currently being revamped)

**Comment by ciscorn** [comment]
@xeho91 With the Hobby plan on Vercel, it’s not possible to create a team. For now, I’ll quickly create the project under my account. If you have any other ideas, please let me know!

**Comment by xeho91** [comment]
That's fine; thanks for letting me know! 🟢 
We can reach out to them later regarding some support for the OSS project if there is/will be any initiative on their side.

**Comment by ciscorn** [comment]
@xeho91 Bad news:

> Deploying from a GitHub organization requires a Vercel Pro plan. Switch to an existing Pro team or upgrade ciscorn's projects to continue.

I’m now considering using my existing Cloudflare Pages/Workers personal account (Pro) instead… 🤔
![Image](https://github.com/user-attachments/assets/17e20b95-01c1-4d8f-ad63-0738bd418b75)

**Comment by xeho91** [comment]
I'm looking at [Netlify](https://netfify.com) as well to see if they would have the same limitation as Vercel.

**Comment by ciscorn** [comment]
Netlify sounds great as well! 😊
